name: Documentation
on:
  push:
    tags:
      - "*"
    branches: [main, master]
permissions:
  contents: read
jobs:
  build:
    name: Build and publish documentation
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit
          disable-telemetry: true
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update
      - name: Setup Cpp
        uses: aminya/setup-cpp@d485b24c1283deafc12b4b8ae90ff09c0d1eb972 # v0.44.0
        with:
          clangtidy: true
      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      - name: Install Docs
        run: |
          sudo apt-get install doxygen
          pip install -r requirements.txt  --require-hashes
      - name: configure
        run: |
          cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Debug"
      - name: building
        run: |
          cmake --build build --config Debug --target doc_doxygen -j4
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@526a34f794dfdf7edd6a4ac94321b1e7945910c0 # v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: ./build/docs/doc_doxygen/html
